ffnord/ffnord-puppet-gateway

- files/usr/local/include/ffnord-update.common
At the ffki-noc we have an null-mailer on every gateway, which reports any output from cron jobs. Therefore all scripts should be as silent as possible, otherwise we get information spamd. Which significantly reduces the problem awareness. 
So this reduces the output in the generic pull case.
> update-common: Drop non error output

- files/usr/local/bin/check-gateway
otherwise packets might get to the main routing table if we
do not have a default route in table 42
> check-gateway: ensure we also have unreachable route

- manifests/resources/fastd.pp
Otherwise the required backports repository may not be enabled,
which would render jq unavailable.
> fastd-query: Add missing dependency.

- manifests/uplink.pp
otherwise local packets are not going through nat.
> uplink: exclude dst addresses instead of src adresses

- files/etc/apt/preferences.d/tinc
- manifests/tinc.pp
as this version is much more stable.
the normal debian version 1.0.19-3 crashes quite frequently on our gateways.
> tinc: ensure we install the debian-backports version

- files/usr/local/bin/update-meta
- manifests/resources/bird.pp
This will store the inclusion information for bird4/6 in /etc/ffnord,
thus we can decide to call reload funcitons on bird4 respective bird6
only if they shall be running.
> bird,meta: Respect inclusion configuration during meta update.

- manifests/ntp.pp
somehow using -6 gives error messages in syslog on startup
and does not apply the rule. omitting the -6, everything works as expected
> ntp: fix syntax of restrict option

- README.md
- files/etc/sysctl.d/routing.conf
- manifests/fastd.pp
- manifests/init.pp
- templates/etc/fastd/fastd.conf.erb
wmem increase to have a send queue of sufficient size.
vpn_mac introduced to allow setting a separate mac for the vpn interface,
otherwise we get a lot of messages like "received packet on bat-ffhh with own address as source address".
as the vpn interface is a client in the mesh and the same holds for the bat interface, these macs should differ.
> fastd improvements

- files/usr/local/bin/maintenance
After a reboot in maintenance mode, after leaving maintenance, the dhcpd
is not started. On the other side it also not stopped when entering
maintenance.  This pr will fix this behaviour.
> maintenance: Stop/Start dhcpd

- manifests/alfred.pp
We start alfred via fastd up script. When the current script is runned
at init then none functional alfred processes are launched.
> alfred: Disable alfred init script.

- files/etc/iptables.d/900-FORWARD-drop
- files/etc/iptables.d/900-INPUT-drop
- files/usr/local/bin/build-firewall
we need to ensure that packets which are not udp or tcp are dropped at the end of the FORWARD and INPUT chain.
in addition to that, rules should be saved after build-firewall is executed. see #101
> Firewall adaptions

- files/etc/zabbix/fastd_connections.sh
- files/etc/zabbix/fastd_connections6.sh
- manifests/fastd.pp
- manifests/monitor/zabbix.pp
the userparameters are suffixed with the respective community name
or the keyword all if a parameter is monitored only once per machine. for the latter
conntrack might be a good example, while a per community monitoring
is needed e.g. for dhcp leases.
in addition to that, fastd is now monitored
> zabbix: allow multi-community monitoring and monitor fastd

- templates/etc/bird/bird6.conf.erb
luebeck is using its new public ipv6 range also for icvpn, so we should include it into the appropriate filter
> bird6: add ff luebeck range

- manifests/alfred.pp
- manifests/firewall.pp
- manifests/resources/meta.pp
- manifests/tinc.pp
Fixed revisions for repositories which are not pulled cron based, but are essential for gateway functionality. This way we can change behavior and upgrade the revisions via puppet script and
don't have to upgrade those manually. This should fix #113.
Also fixing some minor glitches which arise during the last puppet run on ffki-vpn0 and during
the latest test run.
> Fixed revisions

- README.md
- manifests/fastd.pp
- manifests/init.pp
- templates/etc/fastd/fastd.conf.erb
* the new standard is MTU 1280
* added $mesh_interface to ffnord::fastd
* moved old MTU 1426 into example in the README.md as second fastd instances called ${mesh_code}-old
> enable multiple fastd instances with different interface ids

- files/etc/ntp.conf
restrict clauses needed (with IP addresses) otherwise no sync possible,
the high stratum for the local ref clock is set so that it will only
be used if no other server is reachable
> ntp: add restrict clause for each ntp server, high stratum for local ref

- manifests/alfred.pp
Update to latest revision, skipping capability dropping feature,
because of currently not solved dependency.
> alfred: Update to latest rev.

- .travis.yml
- tests/validate.sh
Rebase of #148 
======
Add an Travis Ci script based on @pinguinpfleger in #144
But be aware that puppet-lint is giving a lot of errors. I did use as Test.pp the puppet script from the README.md and did not change anything in the bash script by @pinguinpfleger
If any of the Admins wanna make this validation trough Travis CI: here is the code for it ;) Tested and working.
Admin Infos
---------------
For adding this here are pro and contra:
**Pro:**
- You can add a badge how the state of the build is
- Automatic Puppetmodule validation
**Contra:**
- one of the admins have to login to https://travis-ci.org and must activate the repo there
> Add Travis CI Config for validating puppet module v2

- .travis.yml
Travis CI failed with error "no realease canidate for rubygems".
rumbygems heisst nun ruby. :) mit dieser änderung sollte travis wieder gehen
> Fix travis.ci problems with the rubygems package

- .travis.yml
- tests/validate.sh
Puppet-lint had some troubles with the file structure of this module because the official reference changed. This Pull fix it (Deeper Info is in the commit comments).
> Another Fix for travis

- files/usr/local/bin/update-zones
when called from crontab, debian jessie requires full path to rndc "update-zones"
> add full path for calling rndc in update-zones

- manifests/resources/repos.pp
Otherwise puppet cannot fetch from https://repo.universe-factory.net/
> Install apt-transport-https before fetching fastd sources

- files/usr/local/bin/check-gateway
Mehr logging
- in daemon.log mit dem tag "check-gateway" ausgeben, sowie auf stderr im Fehlerfall, sodass der cronjob auch diese Meldungen enthält.
Daemon die ebenfals nach nichterreichbarkeit der IP beendet/neugestartet werden:
> More logging, (gw|vpn)-watchdog in check-gateway zusammenführen

- manifests/vpn.pp
If I run puppet, I get 
Invalid parameter gw_control_ip at /etc/puppet/modules/ffnord/manifests/vpn.pp:13 
would this fix it? Maybe this is also wrong.
please try out the ffnord-example to fix this.
> Invalid parameter gw_control_ip

- templates/etc/openvpn/pia.conf.erb
route-noexec fehlte in der anonvpn.conf
> PIA: route-noexec ergänzt

- templates/etc/radvd.conf.erb
Als Reaktion auf:
http://freifunk-stuttgart.de/2016/01/22/ipv6-router-advertisements-legen-freifunk-router-lahm/
> Was war passiert?
> 
> Im FFS-Netz war die Anzahl IPv6 Router Advertisement Pakete (RA) auf eine so hohe Zahl gestiegen, dass die Router diese nicht mehr in Echtzeit verarbeiten konnten und sich mehrere parallele Prozesse aufgebaut haben, jeder von einem RA getriggert.
> Im obigen Bild sind es noch 3 Prozesse, die auf den ersten Blick unkritisch scheinen, sie führen jedoch auch zu den kworker Prozessen - in der Summe ist es dann nicht mehr vernachlässigbar. Und die Anzahl steigt stetig.
> Im obigen Bild sind es noch 3 Prozesse, die auf den ersten Blick unkritisch scheinen, sie führen jedoch auch zu den kworker Prozessen – in der Summe ist es dann nicht mehr vernachlässigbar. …
> RADVD: limit RA

- .travis.yml
1.5.1 gibt es nicht mehr 1.5.2 läuft
> puppetlabs-apt --version 1.5.2
